language: node_js
node_js:
  - "12"
  - "10"
  - "8"
env:
  - ESLINT_VERSION=6
  - ESLINT_VERSION=5
  - ESLINT_VERSION=4
install:
  - if [[ $ESLINT_VERSION != "6" ]]; then npm i "eslint@^$ESLINT_VERSION"; fi
  - npm ci
  - npm ls eslint
  - if [[ $ESLINT_VERSION == "6" ]]; then npm run eslint; fi
  