language: node_js
node_js:
  - "10"
  - "8"
env:
  - ESLINT_VERSION=6
  - ESLINT_VERSION=5
install:
  - if [[ $ESLINT_VERSION != "6" ]]; then npm upgrade "eslint@^$ESLINT_VERSION"; fi
  - npm ci
  - if [[ $ESLINT_VERSION == "6" ]]; then npm run eslint; fi
  